name: Generate Portfolio Matrix

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch:

permissions:
  contents: write

jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Matrix
      run: node .github/scripts/portfolio-matrix.js
      
    - name: Deploy Matrix to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        destination_dir: matrix
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: matrix-${{ github.run_number }}
        release_name: 🔮 Portfolio Matrix ${{ github.run_number }}
        body: |
          ## 🔮 Portfolio Matrix Generated!
          
          A new portfolio matrix visualization has been created!
          
          **View the Matrix**: [Click here](https://mananyvas01.github.io/BasePortFolio/matrix/portfolio-matrix.html)
          
          ### What's in the Matrix?
          - 🌟 GitHub activity visualization
          - 📊 Repository statistics
          - 🎨 ASCII art representation
          - 🔥 Dynamic animations
          
          *Generated automatically by GitHub Actions*
        draft: false
        prerelease: false
